// CART CONSTANTS
export const CART_LIST_REQUEST = "CART_LIST_REQUEST";
export const CART_LIST_SUCCESS = "CART_LIST_SUCCESS";
export const CART_LIST_FAIL = "CART_LIST_FAIL";

export const CART_ADD_ITEM_REQUEST = "CART_ADD_ITEM_REQUEST";
export const CART_ADD_ITEM_SUCCESS = "CART_ADD_ITEM_SUCCESS";
export const CART_ADD_ITEM_FAIL = "CART_ADD_ITEM_FAIL";

export const CART_REMOVE_ITEM_REQUEST = "CART_REMOVE_ITEM_REQUEST";
export const CART_REMOVE_ITEM_SUCCESS = "CART_REMOVE_ITEM_SUCCESS";
export const CART_REMOVE_ITEM_FAIL = "CART_REMOVE_ITEM_FAIL";

export const CART_INCREASE_ITEM_REQUEST = "CART_INCREASE_ITEM_REQUEST";
export const CART_INCREASE_ITEM_SUCCESS = "CART_INCREASE_ITEM_SUCCESS";
export const CART_INCREASE_ITEM_FAIL = "CART_INCREASE_ITEM_FAIL";

export const CART_DECREASE_ITEM_REQUEST = "CART_DECREASE_ITEM_REQUEST";
export const CART_DECREASE_ITEM_SUCCESS = "CART_DECREASE_ITEM_SUCCESS";
export const CART_DECREASE_ITEM_FAIL = "CART_DECREASE_ITEM_FAIL";

export const CLEAR_CART_REQUEST = "CLEAR_CART_REQUEST";
export const CLEAR_CART_SUCCESS = "CLEAR_CART_SUCCESS";
export const CLEAR_CART_FAIL = "CLEAR_CART_FAIL";

export const CART_LIST_RESET = "CART_LIST_RESET";
export const CART_UPDATE_RESET = "CART_UPDATE_RESET";
 