export const NOTIFICATION_LIST_REQUEST = "NOTIFICATION_LIST_REQUEST";
export const NOTIFICATION_LIST_SUCCESS = "NOTIFICATION_LIST_SUCCESS";
export const NOTIFICATION_LIST_FAIL = "NOTIFICATION_LIST_FAIL";

export const NOTIFICATION_MARK_READ_REQUEST = "NOTIFICATION_MARK_READ_REQUEST";
export const NOTIFICATION_MARK_READ_SUCCESS = "NOTIFICATION_MARK_READ_SUCCESS";
export const NOTIFICATION_MARK_READ_FAIL = "NOTIFICATION_MARK_READ_FAIL";

export const NOTIFICATION_COUNT_REQUEST = "NOTIFICATION_COUNT_REQUEST";
export const NOTIFICATION_COUNT_SUCCESS = "NOTIFICATION_COUNT_SUCCESS";
export const NOTIFICATION_COUNT_FAIL = "NOTIFICATION_COUNT_FAIL";