export const PAYMENT_CREATE_REQUEST = "PAYMENT_CREATE_REQUEST";
export const PAYMENT_CREATE_SUCCESS = "PAYMENT_CREATE_SUCCESS";
export const PAYMENT_CREATE_FAIL = "PAYMENT_CREATE_FAIL";
export const PAYMENT_CREATE_RESET = "PAYMENT_CREATE_RESET";

export const PAYMENT_LIST_USER_REQUEST = "PAYMENT_LIST_USER_REQUEST";
export const PAYMENT_LIST_USER_SUCCESS = "PAYMENT_LIST_USER_SUCCESS";
export const PAYMENT_LIST_USER_FAIL = "PAYMENT_LIST_USER_FAIL";
export const PAYMENT_LIST_USER_RESET = "PAYMENT_LIST_USER_RESET";

export const PAYMENT_LIST_ALL_REQUEST = "PAYMENT_LIST_ALL_REQUEST";
export const PAYMENT_LIST_ALL_SUCCESS = "PAYMENT_LIST_ALL_SUCCESS";
export const PAYMENT_LIST_ALL_FAIL = "PAYMENT_LIST_ALL_FAIL";

export const PAYMENT_VERIFY_REQUEST = "PAYMENT_VERIFY_REQUEST";
export const PAYMENT_VERIFY_SUCCESS = "PAYMENT_VERIFY_SUCCESS";
export const PAYMENT_VERIFY_FAIL = "PAYMENT_VERIFY_FAIL";
export const PAYMENT_VERIFY_RESET = "PAYMENT_VERIFY_RESET";
