// src/redux/constants/serviceConstants.js

export const SERVICE_LIST_REQUEST = 'SERVICE_LIST_REQUEST';
export const SERVICE_LIST_SUCCESS = 'SERVICE_LIST_SUCCESS';
export const SERVICE_LIST_FAIL = 'SERVICE_LIST_FAIL';

export const PROFESSIONAL_SERVICE_CREATE_REQUEST = 'PROFESSIONAL_SERVICE_CREATE_REQUEST';
  export const PROFESSIONAL_SERVICE_CREATE_SUCCESS = 'PROFESSIONAL_SERVICE_CREATE_SUCCESS';
  export const PROFESSIONAL_SERVICE_CREATE_FAIL = 'PROFESSIONAL_SERVICE_CREATE_FAIL';

export const PROFESSIONAL_LIST_REQUEST = 'PROFESSIONAL_LIST_REQUEST';
export const PROFESSIONAL_LIST_SUCCESS = 'PROFESSIONAL_LIST_SUCCESS';
export const PROFESSIONAL_LIST_FAIL = 'PROFESSIONAL_LIST_FAIL';

export const PROFESSIONAL_SERVICES_REQUEST = 'PROFESSIONAL_SERVICES_REQUEST';
export const PROFESSIONAL_SERVICES_SUCCESS = 'PROFESSIONAL_SERVICES_SUCCESS';
export const PROFESSIONAL_SERVICES_FAIL = 'PROFESSIONAL_SERVICES_FAIL';

// CREATE
export const SERVICE_CREATE_REQUEST = 'SERVICE_CREATE_REQUEST';
export const SERVICE_CREATE_SUCCESS = 'SERVICE_CREATE_SUCCESS';
export const SERVICE_CREATE_FAIL = 'SERVICE_CREATE_FAIL';

// UPDATE
export const SERVICE_UPDATE_REQUEST = 'SERVICE_UPDATE_REQUEST';
export const SERVICE_UPDATE_SUCCESS = 'SERVICE_UPDATE_SUCCESS';
export const SERVICE_UPDATE_FAIL = 'SERVICE_UPDATE_FAIL';
export const SERVICE_UPDATE_RESET = 'SERVICE_UPDATE_RESET';

// DELETE
export const SERVICE_DELETE_REQUEST = 'SERVICE_DELETE_REQUEST';
export const SERVICE_DELETE_SUCCESS = 'SERVICE_DELETE_SUCCESS';
export const SERVICE_DELETE_FAIL = 'SERVICE_DELETE_FAIL';

export const SERVICE_DETAIL_REQUEST = 'SERVICE_DETAIL_REQUEST';
export const SERVICE_DETAIL_SUCCESS = 'SERVICE_DETAIL_SUCCESS';
export const SERVICE_DETAIL_FAIL = 'SERVICE_DETAIL_FAIL';

export const TRENDING_SERVICE_LIST_REQUEST = 'TRENDING_SERVICE_LIST_REQUEST';
export const TRENDING_SERVICE_LIST_SUCCESS = 'TRENDING_SERVICE_LIST_SUCCESS';
export const TRENDING_SERVICE_LIST_FAIL = 'TRENDING_SERVICE_LIST_FAIL';

export const FEATURED_SERVICE_LIST_REQUEST = 'FEATURED_SERVICE_LIST_REQUEST';
export const FEATURED_SERVICE_LIST_SUCCESS = 'FEATURED_SERVICE_LIST_SUCCESS';
export const FEATURED_SERVICE_LIST_FAIL = 'FEATURED_SERVICE_LIST_FAIL';